let mode="Pure Blood",race="Human",race2=null,cls="Knight",phase="mode",keys={},P,enemies=[],last=0,started=false,gold=0,xp=0;
function showSelect(){splash.style.display="none";select.style.display="flex";renderCards()}
function addCard(x,sub,sel,fn){let b=document.createElement("button");b.className="card "+(sel?"sel":"");b.innerHTML="<b>"+x+"</b><br><small>"+sub+"</small>";b.onclick=fn;cards.appendChild(b)}
function renderCards(){cards.innerHTML="";
if(phase==="mode"){creatorHint.textContent="Choose Pure Blood or Hybrid.";["Pure Blood","Hybrid"].forEach(x=>addCard(x,x==="Pure Blood"?"One complete bloodline":"Combine two bloodlines",mode===x,()=>{mode=x;renderCards()}));next.textContent="CHOOSE BLOODLINE"}
else if(phase==="race1"){creatorHint.textContent=mode==="Hybrid"?"Choose the base bloodline.":"Choose your bloodline.";races.forEach(x=>addCard(x,"Bloodline traits",race===x,()=>{race=x;if(race2===x)race2=null;renderCards()}));next.textContent=mode==="Hybrid"?"SECOND BLOODLINE":"CHOOSE CLASS"}
else if(phase==="race2"){creatorHint.textContent="Choose the inherited bloodline.";races.filter(x=>x!==race).forEach(x=>addCard(x,"Inherited signature traits",race2===x,()=>{race2=x;renderCards()}));next.textContent="CHOOSE CLASS"}
else{creatorHint.textContent="Choose class equipment.";classes.forEach(x=>addCard(x,classData[x][0],cls===x,()=>{cls=x;renderCards()}));next.textContent="ENTER THE DARKNESS"}}
next.onclick=()=>{if(phase==="mode"){phase="race1";renderCards()}else if(phase==="race1"){if(mode==="Hybrid"){phase="race2";renderCards()}else{race2=null;phase="class";rt.classList.remove("sel");ct.classList.add("sel");renderCards()}}else if(phase==="race2"){if(!race2)return;phase="class";rt.classList.remove("sel");ct.classList.add("sel");renderCards()}else{select.style.display="none";loading.style.display="flex";setTimeout(()=>lf.style.width="100%",50);setTimeout(begin,1500)}};
